#!/usr/bin/env bash
# build-agent-image.sh - build the agent binary in-container, assemble the runtime image
#
# Ref: ship-server-binary.sh pattern. The compile runs NATIVELY inside the
# local-rust-trixie:builder container (linux/arm64 toolchain - no cross compile,
# no host toolchain deps), with a persistent cargo cache volume for incremental
# builds (first run ~10-20 min, then 2-5 min). Output image agent-agent:latest
# is consumed by .test-agents/restart.sh.
#
# Usage:
#   ./scripts/build-agent-image.sh [--fresh]
#
#   --fresh   wipe the cargo cache volume first (cache pollution triage)

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILDER="local-rust-trixie:builder"
BASE="local-debian-slim:runtime"
CARGO_VOLUME="cyj-agent-cargo"
TARGET_VOLUME="cyj-agent-target"
BIN_NAME="cyber-jianghu-agent"

for img in "$BUILDER" "$BASE"; do
    docker image inspect "$img" > /dev/null 2>&1 \
        || { echo "[error] missing base image $img (bootstrapped by restart.sh --build)"; exit 1; }
done

case "${1:-}" in
    --fresh)
        docker volume rm "$CARGO_VOLUME" "$TARGET_VOLUME" > /dev/null 2>&1 || true
        echo "[cache] cargo/target volumes wiped" ;;
    "") ;;
    *) echo "usage: $0 [--fresh]"; exit 1 ;;
esac

# -- 0. reclaim disposable docker garbage (dangling images + build cache)
# 只清可再生缓存：每次 assemble 都会产生新 dangling 层，旧层无复用价值。
# 不碰 named volumes (cyj-agent-cargo/cyj-agent-target) 与有 tag 镜像，
# 增量 cargo 缓存不受影响（首次 10-20min 重建的成本只在 --fresh 时支付）。
echo "[cache] prune dangling images + build cache"
docker image prune -f 2>/dev/null | tail -n 1 || true
docker builder prune -f 2>/dev/null | tail -n 1 || true
docker system df 2>/dev/null | head -n 5 || true

if [ -n "$(git -C "$PROJECT_ROOT" status --porcelain 2>/dev/null)" ]; then
    echo "[warn] dirty workspace, these files go into the image:"
    git -C "$PROJECT_ROOT" status --short
fi

# -- 1. in-container native build (workspace mount + cargo/target cache volumes)
# CARGO_TARGET_DIR=/target：位于 /work 之外的独立卷。若挂在 /work/target（bind-mount
# 子树内），Docker Desktop 首次挂载会把宿主目录旧产物拷入空卷导致 EEXIST
echo "[build] in-container cargo build --release (cache volumes: $CARGO_VOLUME / $TARGET_VOLUME)"
docker run --rm \
    -v "$PROJECT_ROOT:/work" \
    -v "$CARGO_VOLUME:/usr/local/cargo" \
    -v "$TARGET_VOLUME:/target" \
    -e CARGO_TARGET_DIR=/target \
    -w /work \
    "$BUILDER" \
    bash -c '
set -e
CARGO_HOME=${CARGO_HOME:-/usr/local/cargo}
mkdir -p "$CARGO_HOME"
if [ ! -s "$CARGO_HOME/config.toml" ]; then
    printf "[source.crates-io]\nreplace-with = \"aliyun\"\n\n[source.aliyun]\nregistry = \"sparse+https://mirrors.aliyun.com/crates.io-index/\"\n" \
        > "$CARGO_HOME/config.toml"
fi
cargo build --release -p cyber-jianghu-agent
'
# 从卷中提取二进制到 .bin/（runtime 镜像 COPY 用）
mkdir -p "$PROJECT_ROOT/.bin"
docker run --rm -v "$TARGET_VOLUME:/x:ro" "$BUILDER" \
    cat /x/release/cyber-jianghu-agent > "$PROJECT_ROOT/.bin/agent-bin-linux"
BIN_HASH="$(md5 -q "$PROJECT_ROOT/.bin/agent-bin-linux" 2>/dev/null || md5sum "$PROJECT_ROOT/.bin/agent-bin-linux" | cut -d' ' -f1)"
echo "[build done] md5=$BIN_HASH size=$(du -h "$PROJECT_ROOT/.bin/agent-bin-linux" | cut -f1)"

# -- 2. assemble runtime image (runtime-only, seconds; base has runtime deps) -
DOCKERFILE="$(mktemp /tmp/Dockerfile.agent.XXXXXX)"
cat > "$DOCKERFILE" <<'DOCKERFILE'
# TEMP runtime-only image - generated by build-agent-image.sh, do not edit
FROM __BASE__

RUN groupadd -g 1000 cyberjianghu && \
    useradd -u 1000 -g cyberjianghu -m -s /bin/bash cyberjianghu

WORKDIR /app
COPY .bin/agent-bin-linux /app/agent
RUN chmod +x /app/agent
COPY crates/agent/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
COPY crates/agent/static /app/static
RUN mkdir -p /app/data /app/config && \
    chown -R cyberjianghu:cyberjianghu /app

EXPOSE 23340
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:23340/api/v1/health || exit 1
ENV RUST_LOG=info \
    CYBER_JIANGHU_CONFIG_DIR=/app/config \
    CYBER_JIANGHU_DATA_DIR=/app/data
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["./agent", "run", "--port", "23340"]
DOCKERFILE
sed -i '' "s|__BASE__|$BASE|" "$DOCKERFILE"

echo "[assemble] docker build (runtime-only, seconds)"
( cd "$PROJECT_ROOT" && DOCKER_BUILDKIT=0 docker build -f "$DOCKERFILE" -t agent-agent:latest . ) \
    || { echo "[error] image build failed"; rm -f "$DOCKERFILE"; exit 1; }
rm -f "$DOCKERFILE"
docker tag agent-agent:latest "agent-agent:$(git -C "$PROJECT_ROOT" rev-parse --short HEAD)"

# -- 3. verify: binary executable inside the image ----------------------------
echo "[verify] binary self-check inside image"
docker run --rm --entrypoint /bin/sh agent-agent:latest -c 'test -x /app/agent' \
    || { echo "[fail] image binary verification failed"; exit 1; }
echo "[pass] /app/agent executable"

echo ""
echo "[done] agent-agent:latest ready (HEAD $(git -C "$PROJECT_ROOT" rev-parse --short HEAD) changes included)"
echo "  next: .test-agents/restart.sh --register  # restart with the new image and register fresh characters"
